import { api } from "@/utils/api";
import Head from "next/head";
import { FormEventHandler, useRef } from "react";


export default function Home() {
  const ref = useRef()
  const createUser = api.router.user.create.useMutation()
  const handleSubmit = async(e:FormEventHandler)=>{
    e.preventDefault()
    const data = new FormData(ref.current as HTMLFormElement)
    const name = data.get('name') ?? '' 
    const passwordhash = data.get('passwordhash') ?? '' 
    const classs = data.get('class') ?? '' 
    const section = data.get('section') ?? '' 
    console.log(name, passwordhash, classs, section)
    try {
      await createUser.mutateAsync({username: name, passwordHash: passwordhash, role: 'student', class: classs, section: section})

    } catch (error) {
      console.log(error)
    }
  }
  console.log(createUser.isPending, createUser)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form ref={ref} onSubmit={handleSubmit} className="flex flex-col gap-4">
          <input name="name" placeholder="name"></input>
          <input name='passwordhash' placeholder='passwordhash'></input>
          <input name="class" placeholder="class"></input>
          <input name="section" placeholder="section"></input>
          <button className="bg-white p-2" onClick={handleSubmit} type="submit">Submit</button>
        </form>
      </main>
    </>
  );
}
